import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '../src/component/Header';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full`}>
        {/* Ensure you import your actual header component */}
        <Header />
        {children}
      </body>
    </html>
  );
}
